name: Checkity Upload
author: checkity.io
description: Uploads code coverage reports to [checkity.io](https://checkity.io)
branding:
  color: blue
  icon: check-square
runs:
  using: docker
  image: docker://checkity/upload:v1
inputs:
  annotations-enabled:
    default: 'true'
    description: |
      If true, annotations are added for lines missing coverage on pull requests.
    required: false
  annotations-level:
    default: 'NOTICE'
    description: |
      Level to use for annotations. Valid values are FAILURE, NOTICE or WARNING.
    required: false
  badge-enabled:
    default: 'false'
    description: |
      If true, a coverage badge is generated.
    required: false
  badge-label:
    default: checkity.io
    description: |
      Label to use for the generated coverage badge.
      Defaults to `checkity.io` and cannot be changed for public repositories.
      Must match regex `[a-zA-Z0-9._-]{1,20}`.
    required: false
  badge-token:
    description: |
      Token to use for the generated coverage badge, if not specified a badge is not generated.
      The generated badge will be available at https://badge.checkity.io/<owner>/<repo>/<token>.svg
      Must match regex `[a-zA-Z0-9_-]{0,20}`.
    required: false
  base-enabled:
    default: 'true'
    description: |
      If true, the base coverage check is enabled.
    required: false
  diff-enabled:
    default: 'true'
    description: |
      If true, the diff coverage check is enabled.
    required: false
  diff-target:
    default: '1'
    description: |
      Target for diff coverage.
    required: false
  file-pattern:
    description: Comma separated list of coverage files to upload, supports globs.
    required: true
  overall-enabled:
    default: 'true'
    description: |
      If true, the overall coverage check is enabled.
    required: false
  overall-target:
    default: '0.8'
    description: |
      Target for overall coverage.
    required: false
  repo-token:
    description: The GitHub token used to validate repository access when uploading coverage reports.
    required: true
